### ISSUE TITLE
cv ext:enable fails with these errors

### ISSUE THREAD

**Issue by hesco** [progressivetech/com.aghstrategies.petitionemail#4]
My attempt to enable this extension was answered with this.  Any thoughts on how I might resolve this?

```
jenkins@efc9c26-01112:~/sites/${project_code}$ vendor/bin/cv ext:enable com.aghstrategies.petitionemail 
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /opt/local/${project_code}/files/civicrm/ext/chasse/chasse.civix.php on line 246
Deprecated: Array and string offset access syntax with curly braces is deprecated in /opt/local/${project_code}/files/civicrm/ext/chasse/chasse.civix.php on line 246
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /opt/local/${project_code}/files/civicrm/ext/biz.lcdservices.civizoom-2.2/civizoom.civix.php on line 246
Deprecated: Array and string offset access syntax with curly braces is deprecated in /opt/local/${project_code}/files/civicrm/ext/biz.lcdservices.civizoom-2.2/civizoom.civix.php on line 246
Enabling extension "com.aghstrategies.petitionemail"
Error: API Call Failed: Array
(
    [entity] => Extension
    [action] => install
    [params] => Array
        (
            [keys] => Array
                (
                    [0] => com.aghstrategies.petitionemail
                )

            [debug] => 1
            [version] => 3
        )

    [result] => Array
        (
            [trace] => #0 /opt/local/${project_code}/drupal/vendor/civicrm/civicrm-core/CRM/Core/ManagedEntities.php(249): CRM_Core_ManagedEntities->onApiError()
#1 /opt/local/${project_code}/drupal/vendor/civicrm/civicrm-core/CRM/Core/ManagedEntities.php(144): CRM_Core_ManagedEntities->updateExistingEntity()
#2 /opt/local/${project_code}/drupal/vendor/civicrm/civicrm-core/CRM/Core/ManagedEntities.php(112): CRM_Core_ManagedEntities->reconcileEntities()
#3 /opt/local/${project_code}/drupal/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php(413): CRM_Core_ManagedEntities->reconcile()
#4 /opt/local/${project_code}/drupal/vendor/civicrm/civicrm-core/CRM/Extension/Manager.php(314): CRM_Core_Invoke::rebuildMenuAndCaches()
#5 /opt/local/${project_code}/drupal/vendor/civicrm/civicrm-core/api/v3/Extension.php(42): CRM_Extension_Manager->install()
#6 /opt/local/${project_code}/drupal/vendor/civicrm/civicrm-core/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_extension_install()
#7 /opt/local/${project_code}/drupal/vendor/civicrm/civicrm-core/Civi/API/Kernel.php(149): Civi\API\Provider\MagicFunctionProvider->invoke()
#8 /opt/local/${project_code}/drupal/vendor/civicrm/civicrm-core/Civi/API/Kernel.php(81): Civi\API\Kernel->runRequest()
#9 /opt/local/${project_code}/drupal/vendor/civicrm/civicrm-core/api/api.php(22): Civi\API\Kernel->runSafe()
#10 /opt/local/${project_code}/drupal/vendor/civicrm/cv/src/Command/BaseCommand.php(63): civicrm_api()
#11 /opt/local/${project_code}/drupal/vendor/civicrm/cv/src/Command/ExtensionEnableCommand.php(91): Civi\Cv\Command\BaseCommand->callApiSuccess()
#12 /opt/local/${project_code}/drupal/vendor/symfony/console/Command/Command.php(255): Civi\Cv\Command\ExtensionEnableCommand->execute()
#13 /opt/local/${project_code}/drupal/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#14 /opt/local/${project_code}/drupal/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#15 /opt/local/${project_code}/drupal/vendor/civicrm/cv/src/Application.php(59): Symfony\Component\Console\Application->doRun()
#16 /opt/local/${project_code}/drupal/vendor/symfony/console/Application.php(149): Civi\Cv\Application->doRun()
#17 /opt/local/${project_code}/drupal/vendor/civicrm/cv/src/Application.php(26): Symfony\Component\Console\Application->run()
#18 /opt/local/${project_code}/drupal/vendor/civicrm/cv/bin/cv(28): Civi\Cv\Application::main()
#19 {main}
            [is_error] => 1
            [error_message] => API error: DB Error: no such field on OptionGroup.create( entity name afform_type)
        )

)
```

**Comment by hesco** [comment]
Having manually worked through the issues related to incomplete past upgrades, I was able to successfully install this module; at least according to the extensions page.  However, I am still not seeing the documented behavior on the petition create form.  See another ticket for a description of the latest issues.
